/* INSERT CATEGORY */
INSERT INTO CATEGORY VALUES(1, '한식');
INSERT INTO CATEGORY VALUES(2, '분식');
INSERT INTO CATEGORY VALUES(3, '카페/디저트');
INSERT INTO CATEGORY VALUES(4, '패스트푸드');
INSERT INTO CATEGORY VALUES(5, '중식');
INSERT INTO CATEGORY VALUES(6, '일식');
INSERT INTO CATEGORY VALUES(7, '양식');
INSERT INTO CATEGORY VALUES(8, '패밀리레스토랑');

