/* CREATE SEQUENCE */
CREATE SEQUENCE HOTPLACE_SEQ START WITH 0 MINVALUE 0 INCREMENT BY 1 NOCACHE; -- HOTPLACE ½ÃÄö½º
CREATE SEQUENCE HREPLY_SEQ START WITH 0 MINVALUE 0 INCREMENT BY 1 NOCACHE; -- HOTPLACE REPLY ½ÃÄö½º
CREATE SEQUENCE BORAD_SEQ START WITH 0 MINVALUE 0 INCREMENT BY 1 NOCACHE; -- BOARD ½ÃÄö½º
CREATE SEQUENCE B_REPLY_SEQ START WITH 0 MINVALUE 0 INCREMENT BY 1 NOCACHE; -- BOARD REPLY ½ÃÄö½º